### ISSUE TITLE
April Forecast Actuals Checklist

### ISSUE THREAD

**Issue by mary-curd** [mary-curd/support-forecast-capacity#1]
### Enterprise

- [ ] Seat Counts
- [ ] Total Tickets
- [ ] Total Public Comments
- [ ] Headcounts
- [ ] Calculate IPX
- [ ] Calculate Touches per Case
- [ ] Calculate Time per Touch

### Developer

- [ ] Seat Counts
- [ ] Total Tickets
- [ ] Total Public Comments
- [ ] Headcounts
- [ ] Calculate IPX
- [ ] Calculate Touches per Case
- [ ] Calculate Time per Touch

### Premium

- [ ] Seat Counts
- [ ] Total Tickets
- [ ] Total Public Comments
- [ ] Headcounts
- [ ] Calculate IPX
- [ ] Calculate Touches per Case
- [ ] Calculate Time per Touch
